session:
  parameter: language
url:
  source: domain
  prefixes:
    en: ''
    es: es
    fr: fr
  domains:
    en: mysite.com
    es: es.mysite.com
    fr: fr.mysite.com
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
